// Generated by FlutterFire CLI — project: vacanca-app (Vacansa app).
// Re-run: flutterfire configure --project=vacanca-app

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Firebase not configured for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9R8fZi5rNCh5Udx_qmfYk_GaL8Uka1YQ',
    appId: '1:238424492626:web:8f0fc5890c7ca3036eed8b',
    messagingSenderId: '238424492626',
    projectId: 'vacanca-app',
    authDomain: 'vacanca-app.firebaseapp.com',
    storageBucket: 'vacanca-app.firebasestorage.app',
    measurementId: 'G-9PCV9T9LHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDuOp8NeccJr9nSm-KqqZTPIHEaqxzHDo',
    appId: '1:238424492626:android:fc29e9398fc7773b6eed8b',
    messagingSenderId: '238424492626',
    projectId: 'vacanca-app',
    storageBucket: 'vacanca-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCZqXdDelkz6v7NvdcIWpyqiWSnoDXfM',
    appId: '1:238424492626:ios:6ca534c648eb1fc06eed8b',
    messagingSenderId: '238424492626',
    projectId: 'vacanca-app',
    storageBucket: 'vacanca-app.firebasestorage.app',
    iosBundleId: 'com.codesolution.vacansa',
  );
}
